// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "skype4business",
    "name": "Skype for Business",
    "description": "Skype for Business plugin for Mattermost.",
    "homepage_url": "https://github.com/mattermost/mattermost-plugin-skype4business",
    "support_url": "https://github.com/mattermost/mattermost-plugin-skype4business/issues",
    "release_notes_url": "https://github.com/mattermost/mattermost-plugin-skype4business/releases/tag/v0.2.0",
    "icon_path": "assets/profile.svg",
    "version": "0.2.0",
    "min_server_version": "5.10.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "To report an issue, make a suggestion or a contribution, [check the repository](https://github.com/mattermost/mattermost-plugin-skype4business).",
        "settings": [
            {
                "key": "productType",
                "display_name": "Skype for Business Product Type",
                "type": "radio",
                "help_text": "The product type of your Skype for Business instance.",
                "placeholder": "",
                "default": "Server",
                "options": [
                    {
                        "display_name": "Server",
                        "value": "server"
                    },
                    {
                        "display_name": "Online",
                        "value": "online"
                    }
                ]
            },
            {
                "key": "Username",
                "display_name": "Skype for Business Bot Username",
                "type": "text",
                "help_text": "Username of your selected bot account. We strongly recommend using a dedicated bot account for this plugin, rather than an existing Skype for Business user account. Only required for Skype for Business Server.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "Password",
                "display_name": "Skype for Business Bot Password",
                "type": "text",
                "help_text": "Password of your selected bot account. Only required for Skype for Business Server.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "Domain",
                "display_name": "Server Domain",
                "type": "text",
                "help_text": "The domain of your Skype for Business server instance. For example, contoso.com. Only required for Skype for Business Server.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "ClientId",
                "display_name": "Application ID",
                "type": "text",
                "help_text": "Application ID from the Azure Active Directory. Only required for Skype for Business Online. Use this URL to configure the plugin in Azure Active Directory: https://SITEURL/plugins/skype4business/api/v1/auth_redirect",
                "placeholder": "",
                "default": null
            }
        ]
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
